---
# Create Test Resources
- name: Create test deployment and ingress
  when: inventory_hostname == k3s_primary_control_node
  block:
    - name: Create test deployment and service
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: test-nginx
              namespace: default
            spec:
              replicas: 3
              selector:
                matchLabels:
                  app: test-nginx
              template:
                metadata:
                  labels:
                    app: test-nginx
                spec:
                  containers:
                    - name: nginx
                      image: nginx:alpine
                      ports:
                        - containerPort: 80
          - apiVersion: v1
            kind: Service
            metadata:
              name: test-nginx
              namespace: default
            spec:
              type: LoadBalancer
              selector:
                app: test-nginx
              ports:
                - port: 80
                  targetPort: 80
                  protocol: TCP

    - name: Create test ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: test-nginx
            namespace: default
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            ingressClassName: nginx
            rules:
              - host: test.k3s.local
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: test-nginx
                          port:
                            number: 80

    - name: Get LoadBalancer IPs
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: default
        kubeconfig: "{{ kubeconfig }}"
      register: services

    - name: Display cluster information
      ansible.builtin.debug:
        msg: |
          K3s cluster deployed successfully!

          Control Planes:
          {% for node in groups['k3s_servers'] %}
          - {{ node }}: {{ hostvars[node]['ansible_default_ipv4']['address'] }}
          {% endfor %}

          {% if groups['k3s_workers'] is defined %}
          Workers:
          {% for node in groups['k3s_workers'] %}
          - {{ node }}: {{ hostvars[node]['ansible_default_ipv4']['address'] }}
          {% endfor %}
          {% endif %}

          MetalLB IP Range: {{ metallb_ip_range }}

          Test the setup:
          1. Check MetalLB assigned IPs:
             kubectl get svc -A | grep LoadBalancer

          2. Test NGINX Ingress:
             curl -H "Host: test.k3s.local" http://<METALLB_IP>

          3. To access services, add entries to /etc/hosts:
             <METALLB_IP> test.k3s.local
